# Generated by Django 6.1.2 on 2026-10-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='donor_photos/')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField(default=24)),
                ('district', models.CharField(default='Dhaka', max_length=50)),
                ('upazila', models.CharField(default='Dhanmondi', max_length=50)),
                ('area', models.CharField(default='Dhanmondi, Dhaka', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('last_donated_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(default='+880 1712-345678', max_length=20)),
                ('whatsapp_number', models.CharField(default='+880 1712-345678', max_length=20)),
                ('email', models.EmailField(default='donor@gmail.com', max_length=254)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('occupation', models.CharField(default='Software Engineer', max_length=100)),
                ('languages', models.CharField(default='Bangla, English', max_length=100)),
                ('about_me', models.TextField(default='I am happy to help save lives. Feel free to contact me.')),
                ('total_donations', models.IntegerField(default=5)),
                ('distance_km', models.FloatField(default=0.8)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_histories', to='donors.donor')),
            ],
        ),
    ]
