# Generated by Django 6.1.1 on 2026-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=150)),
                ('hospital_name', models.CharField(max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_days', models.CharField(max_length=100)),
                ('visiting_hours', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
