# Generated by Django 6.1.2 on 2026-10-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(default='Dhanmondi, Dhaka', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitals/')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('reviews_count', models.IntegerField(default=120)),
                ('total_beds', models.IntegerField(default=300)),
                ('total_doctors', models.IntegerField(default=24)),
                ('distance', models.CharField(default='1.2 km away', max_length=50)),
                ('helpline', models.CharField(default='09612-345678', max_length=50)),
                ('emergency_contact', models.CharField(default='01713-456789', max_length=50)),
                ('email', models.EmailField(default='info@labaidgroup.com', max_length=254)),
                ('website', models.URLField(default='https://www.labaidgroup.com')),
                ('description', models.TextField(blank=True)),
                ('has_icu', models.BooleanField(default=True)),
                ('has_ccu', models.BooleanField(default=True)),
                ('has_nicu', models.BooleanField(default=True)),
                ('has_emergency', models.BooleanField(default=True)),
                ('has_ambulance', models.BooleanField(default=True)),
                ('has_pharmacy', models.BooleanField(default=True)),
            ],
        ),
    ]
